### PR TITLE
fix: update source of isDarkTheme

### PR DESCRIPTION
**Pull request by oil-oil**
fix: #161

### CODE REVIEW

**Comment by rohit-gohri** [comment]
@oil-oil Thanks for the contribution! Can you also update docusaurus.beta version to latest? Since the color mode changes happened in latest version

**Comment by oil-oil** [comment]
> @oil-oil Thanks for the contribution! Can you also update docusaurus.beta version to latest? Since the color mode changes happened in latest version

Okay, no problem.

**Comment by oil-oil** [comment]
@rohit-gohri I don't know if I updated the dependencies correctly, if there are problems you can give me feedback.

**Review by rohit-gohri — APPROVED** [review]

**Comment by rohit-gohri** [comment]
Thanks for the PR, it's released in [v1.0.3](https://github.com/rohit-gohri/redocusaurus/releases/tag/v1.0.3)

**Pull request merged**
