### PR TITLE
Remove `useThemeContext` and switch to the new `useColorMode` added in Canary.

### LINKED ISSUE #116: Docusaurus Canary - Can't resolve useThemeContext
Running against Docusaurus canary (which has some fixes for docs sidebar issues - redocusaurus is throwing an error: 

```
Module not found: Error: Can't resolve '@theme/hooks/useThemeContext' in 'X:\Development\Repositories\CIPP Project\website\node_modules\docusaurus-theme-redoc\dist-jsx\theme\Redoc'
```

It appears similar to #96 and looks to be caused by this breaking change: https://github.com/facebook/docusaurus/pull/6289

### PR DESCRIPTION
**Pull request by homotechsual**
Closes #116

### CODE REVIEW

**Comment by homotechsual** [comment]
Fixes #117

**Comment by rohit-gohri** [comment]
I will also update the dependencies and then merge this, currently it breaks the build. Thanks for the PR

**Comment by tanepiper** [comment]
Hi, I'm actually just looking into using this tool and I'm getting this error - when do you think it can be looked at to be merged? We need to serve a lot of OpenAPI docs and this looks like a good tool :)

**Comment by edumaciel10** [comment]
This it's so good

**Comment by slorber** [comment]
sorry for the annoyance, maybe we should provide something to make it retrocompatible?

**Comment by rohit-gohri** [comment]
Merging with failed build, fixing build in this follow up PR: #119
Release should be up soon

**Comment by rohit-gohri** [comment]
Release is up: https://github.com/rohit-gohri/redocusaurus/discussions/122

**Comment by rohit-gohri** [comment]
> sorry for the annoyance, maybe we should provide something to make it retrocompatible?

@slorber Might be nice, but I'm thinking if we can better declare this dependency b/w plugins<->docusaurus via peerDependencies? I don't currently add Docusaurus as a peer dependency, should I add it? I'm not sure how that would look like

**Comment by slorber** [comment]
@rohit-gohri now you should add this `@docusaurus/theme-common` package as a dependency as you use it, so if we do changes on it, you may notice more easily if TS does not compile anymore

**Pull request merged**
